### ISSUE TITLE
Build fails at cmake stage in Debian

### ISSUE THREAD

**Issue by wladich** [avast-tl/yaramod#1]
I tried to build on clean Debian system (in Docker) following steps in readme file.
I get error when trying to run cmake:
```
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
/retdec/deps/fnc-patterns/deps/yaramod/src/FLEX_INCLUDE_DIR
   used as include directory in directory /retdec/deps/fnc-patterns/deps/yaramod/src
-- Configuring incomplete, errors occurred!
```

**Comment by s3rvac** [comment]
Hi. From the output, I see that you are building [retdec](https://github.com/avast-tl/retdec). You will need to install all the required packages specified in the [Build and Installation](https://github.com/avast-tl/retdec#build-and-installation) section of the README file. From the error message, it seems to me that you do not have [Flex](https://www.gnu.org/software/flex/) installed.

If installing all the required packages does not solve your build issue, could you please share with us your `Dockerfile` so we can investigate this further?

**Comment by wladich** [comment]
Sorry, posted to wrong repo. 
Seems like problem was due to "--no-install-recommends" option I added to apt-get invocation. Without it cmake works fine. Closing issue.
